name: Executes process associated with release.  

on:
  push:
    branches: [ "release-workflow" ]

#on:
#  release:
#    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Parser
      id: parser
      uses: johngeorgewright/parse-version-action
      with:
        ref: ${{ github.ref }}
        trim-start: v

    - name: Debug
      run: echo 'version = ${{ steps.parser.outputs.version }}'

