name: Executes process associated with release.  

on:
  push:
    branches: [ "release-workflow" ]

#on:
#  release:
#    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Parser  
      id: parser
      uses: johngeorgewright/parse-version-action@v2.0.0
      with:
        ref: refs/tags/v1.0.0-test
        trim-start: v

    - name: Debug
      run: echo 'version = ${{ steps.parser.outputs.version }}'

